# Generated by Django 3.1.7 on 2021-05-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('duration', models.CharField(choices=[('2', 'Two Week'), ('3', 'Three Week')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('W', 'Working'), ('U', 'Upgrading'), ('B', 'Broken')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('number', models.IntegerField(default=0)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField(blank=True, null=True)),
                ('day', models.CharField(choices=[('1MWF', 'Shift 1 Mon Wed Fri'), ('2MWF', 'Shift 2 Mon Wed Fri'), ('1TTS', 'Shift 1 Tue Thu Sat'), ('2TTS', 'Shift 2 Tue Thu Sat'), ('1F', 'Shift 1 All Week'), ('2F', 'Shift 2 All Week')], max_length=4)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
        ),
    ]
