# Generated by Django 3.1.7 on 2021-06-08 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=255)),
                ('number', models.IntegerField(default=0)),
                ('number_student', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('day', models.CharField(choices=[('1MWF', 'Shift 1 Mon Wed Fri'), ('2MWF', 'Shift 2 Mon Wed Fri'), ('1TTS', 'Shift 1 Tue Thu Sat'), ('2TTS', 'Shift 2 Tue Thu Sat'), ('1F', 'Shift 1 All Week'), ('2F', 'Shift 2 All Week')], max_length=4)),
                ('status', models.CharField(choices=[('DONE', 'Đã hoàn thành'), ('DOING', 'Đang học'), ('CANCELED', 'Đã huỷ'), ('WAITING', 'Đang chờ'), ('LOCKED', 'Đã khoá lớp')], default='WAITING', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('duration', models.IntegerField(choices=[(3, '3 Weeks'), (4, '4 Weeks'), (5, '5 Weeks'), (6, '6 Weeks')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('W', 'Working'), ('U', 'Upgrading'), ('B', 'Broken')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=13, null=True)),
                ('classes', models.ManyToManyField(blank=True, null=True, related_name='students', to='core.Class')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
                ('weekID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.week')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.course'),
        ),
    ]
