# Generated by Django 3.1.7 on 2021-05-22 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room'),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
