# Generated by Django 3.1.7 on 2021-06-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('W', 'Working'), ('U', 'Upgrading'), ('B', 'Broken')], default='W', max_length=1),
        ),
    ]
