# Generated by Django 3.1.7 on 2021-05-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210522_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='status',
            field=models.CharField(blank=True, choices=[('DONE', 'Đã hoàn thành'), ('DOING', 'Đang học'), ('CANCELED', 'Đã huỷ'), ('WAITING', 'Đang chờ')], default='WAITING', max_length=8, null=True),
        ),
    ]
