# Generated by Django 3.1.7 on 2021-05-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_class_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('DONE', 'Đã hoàn thành'), ('DOING', 'Đang học'), ('CANCELED', 'Đã huỷ'), ('WAITING', 'Đang chờ')], default='WAITING', max_length=8),
        ),
    ]
