# Generated by Django 3.1.7 on 2021-05-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210524_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('2W', 'Two Weeks'), ('3W', 'Three Weeks')], max_length=2),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('birth', models.DateField(blank=True, null=True)),
                ('classes', models.ManyToManyField(to='core.Class')),
            ],
        ),
    ]
