# Generated by Django 3.1.7 on 2021-05-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210527_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('DONE', 'Đã hoàn thành'), ('DOING', 'Đang học'), ('CANCELED', 'Đã huỷ'), ('WAITING', 'Đang chờ'), ('LOCKED', 'Đã khoá lớp')], default='WAITING', max_length=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('9', '9 Days'), ('15', '15 Days'), ('21', '20 Days')], max_length=2),
        ),
    ]
