# Generated by Django 3.1.7 on 2021-05-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210530_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='core.Class'),
        ),
    ]
